name: Docker Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build --no-cache -t ramata:latest .

      # This step demonstrates running the Docker image,
      # but in a CI environment, you might deploy or test instead.
      - name: Run Docker Image
        run: docker run -p 3000:3000 -d ramata:latest

      # This step shows how to echo a success message.
      # GitHub Actions automatically shows failure messages if a step fails.
      - name: Success Message
        run: echo 'The Docker image was successfully running on port 3000.'

    # GitHub Actions doesn't support a direct equivalent to Jenkins' post section,
    # but you can use job outputs, steps.if, and job-level if conditions to manage cleanup.
    # Below is a simple approach to always attempt cleanup, even if previous steps fail.
    # Adjust according to your needs.
    cleanup:
      if: always()
      needs: build-and-run
      runs-on: ubuntu-latest
      steps:
        - name: Cleanup
          run: |
            docker stop $(docker ps -q --filter ancestor=ramata:latest)
            docker rm $(docker ps -aq --filter ancestor=ramata:latest)
            docker rmi ramata:latest
          continue-on-error: true
